spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_db
    username: localuser
    password: localpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always